"""
recursive_agents.agent_a1.agent_a1_engine — the IPP Objects (Ω_k) of the agent_a1 engine node.

Generated by the recursive compiler from the engine template. Three
channels, each a handler factory closing over the live engine bound by Γ
(GraphContext.bindings["engine"]):

  ground       — materialize the local graph + encoder evidence
  chat         — the full agent loop (LLM function calling over the
                 agent_* construction suite + the shared tools node)
  chat_stream  — the observable loop as a collected event stream

The AGENT-CONSTRUCTION capability lives in the agent's TOOLS node
(recursive_agents.agent_a1.agent_a1_tools) — this engine is the loop; the tools are the hands.
"""
from __future__ import annotations

from typing import Any


def make_ground_handler(bindings: dict):
    engine = bindings["engine"]

    def handler(payload: dict, context: dict) -> str:
        return engine.ground(payload.get("task", ""),
                             payload.get("node_id"))

    return handler


def make_chat_handler(bindings: dict):
    engine = bindings["engine"]

    def handler(payload: Any, context: dict) -> dict:
        if isinstance(payload, str):
            task, node_id = payload, None
        else:
            task = payload.get("task", "")
            node_id = payload.get("node_id")
        answer, trace = engine.run_with_trace(task, node_id=node_id)
        return {"answer": answer, "trace": trace,
                "tokens": engine._session_tokens}

    return handler


def make_chat_stream_handler(bindings: dict):
    engine = bindings["engine"]

    def handler(payload: Any, context: dict) -> dict:
        if isinstance(payload, str):
            task, node_id = payload, None
        else:
            task = payload.get("task", "")
            node_id = payload.get("node_id")
        events = []
        answer = ""
        for ev in engine.chat_stream(task, node_id=node_id):
            entry = {"type": ev.type}
            if ev.tool:
                entry["tool"] = ev.tool
            if ev.args is not None:
                entry["args"] = ev.args
            if ev.content is not None:
                entry["content"] = ev.content
            if ev.error is not None:
                entry["error"] = ev.error
            events.append(entry)
            if ev.type == "text":
                answer += ev.content or ""
        return {"events": events, "answer": answer.strip()}

    return handler
