"""Quick import test for agent_a2 generated by agent_a1."""
import sys, json
sys.path.insert(0, '.')

# Test imports
import recursive_agents.agent_a2.agent_a2_engine.IPP_executor
import recursive_agents.agent_a2.agent_a2_tools.IPP_executor
print("agent_a2 engine + tools imports: OK")

from recursive_agents.agent_a2.agent_a2_engine.engine import AgentA1Engine
print("AgentA1Engine importable from agent_a2 package: OK")

# Verify IPP.json files
j = json.loads(open('recursive_agents/agent_a2/agent_a2_engine/IPP.json', encoding='utf-8').read())
print(f"engine IPP.json: node_id={j['node_id']}")
for c in j['channels']:
    print(f"  channel: {c['channel_id']}, handler={c['handler'][:60]}...")

j2 = json.loads(open('recursive_agents/agent_a2/agent_a2_tools/IPP.json', encoding='utf-8').read())
print(f"tools IPP.json: node_id={j2['node_id']}")
for c in j2['channels']:
    handler = c.get('handler', '')[:60]
    print(f"  channel: {c['channel_id']}, handler={handler}")

import os
root = 'recursive_agents/agent_a2'
total = sum(1 for dp, dns, fns in os.walk(root) for f in fns if not dp.endswith('__pycache__'))
print(f"\nTotal files in agent_a2: {total}")
print("ALL CHECKS PASSED")
