"""
agent_happy_engine — the engine of the first recursive agent, level 1.

This engine is NOT weaker than assets/copilot_agent_engine. It carries:
  - AgentA1Engine        — the full agentic loop with LLM function calling
  - HookSystem            — lifecycle hooks (session_start, stop, tool_pre/post, compaction)
  - PromptAssembler       — composable system prompt assembly
  - AutopilotController   — task completion detection
  - ContextSummarizer     — intelligent context compaction

Built strictly per IPP v0.2.8. Generated by the recursive compiler from
the engine template; this is the FIRST COMPILATION of the adaptive chain.

The agent-construction capability lives in agent_happy_tools — this engine
is the LOOP; the tools node is the HANDS.
"""
from .engine import AgentA1Engine, ToolCallEvent, TurnContext, AgentMode
from .hooks import HookSystem, HookContext, HookResult
from .prompt_assembler import PromptAssembler, PromptContext
from .autopilot import AutopilotController, AutopilotState
from .summarizer import ContextSummarizer, SummaryResult
