"""
recursive_agents.agent_happy.agent_happy_engine — the IPP Executors (Ξ_k) of the agent_happy engine node.

Generated by the recursive compiler from the engine template. The base
class enforces ι → π → Ω → ι → ρ → τ* (Axiom X1–X9); the extras record
the observable trace stats in the hash-chained audit record.
"""
from __future__ import annotations

from IPP.IPP_executor import IPPExecutor


class AgentExecutor(IPPExecutor):
    """Ξ for an engine channel — records trace/tool-call stats in the audit."""

    def _record_extras(self, record: dict, envelope, out) -> None:
        if isinstance(out, dict):
            trace = out.get("trace") or []
            if trace:
                record["trace_steps"] = len(trace)
                record["tool_calls"] = sum(
                    1 for t in trace if t.get("type") == "tool_call")
            if out.get("answer") is not None:
                record["answer_len"] = len(str(out["answer"]))
