"""
recursive_agents.runtime.templates — the SOURCE templates rendered per
agent by the AgentToolkit's agent_generate tool, plus a `build()` helper
that materializes a1's initial folders from the raw sources.

The F-file / Ω / Ξ / README / prompt sources are plain strings here so
that a1's own agent_generate tool can render them (it reads these same
sources from disk at runtime — this module is the single source).
"""
from __future__ import annotations

import json
from pathlib import Path

_TPL = Path(__file__).resolve().parent

ENGINE_IPP_JSON = (_TPL / "engine_IPP.json").read_text(encoding="utf-8")
TOOLS_IPP_JSON = (_TPL / "tools_IPP.json").read_text(encoding="utf-8")
ENGINE_IPP_OBJECT_SRC = (_TPL / "engine_IPP_object.py").read_text(
    encoding="utf-8")
ENGINE_IPP_EXECUTOR_SRC = (_TPL / "engine_IPP_executor.py").read_text(
    encoding="utf-8")
TOOLS_IPP_OBJECT_SRC = (_TPL / "tools_IPP_object.py").read_text(
    encoding="utf-8")
TOOLS_IPP_EXECUTOR_SRC = (_TPL / "tools_IPP_executor.py").read_text(
    encoding="utf-8")
README_AGENT = (_TPL / "README_agent.md").read_text(encoding="utf-8")
README_ENGINE = (_TPL / "README_engine.md").read_text(encoding="utf-8")
README_TOOLS = (_TPL / "README_tools.md").read_text(encoding="utf-8")
SYSTEM_PROMPT = (_TPL / "system_prompt.md").read_text(encoding="utf-8")

LOG_DIR = "recursive_agents/graph_data/logs/IPP"


def render(text: str, name: str, node_id: str, engine_pkg: str,
           tools_pkg: str, level: int, generated_by: str) -> str:
    return (text
            .replace("{node_id}", node_id)
            .replace("{agent_id}", name)
            .replace("{engine_pkg}", engine_pkg)
            .replace("{tools_pkg}", tools_pkg)
            .replace("{log_dir}", LOG_DIR)
            .replace("__AGENT_ID__", name)
            .replace("__ENGINE_PKG__", engine_pkg)
            .replace("__TOOLS_PKG__", tools_pkg)
            .replace("__NODE_ID__", node_id)
            .replace("__LEVEL__", str(level))
            .replace("__GENERATED_BY__", generated_by))


def build(name: str, engine_name: str, tools_name: str,
          level: int = 1, generated_by: str = "the recursive compiler",
          root: str = "") -> tuple[Path, Path]:
    """Materialize <name>/<engine_name> + <tools_name> folders from the
    raw template sources (used to build agent_a1; agent_generate uses the
    same rendering for every later agent). Returns (engine_f, tools_f)."""
    base = Path(root) if root else _TPL.parents[2] / "recursive_agents"
    if base.name != "recursive_agents":
        base = base / "recursive_agents"
    agent_dir = base / name
    engine_dir = agent_dir / engine_name
    tools_dir = agent_dir / tools_name
    engine_pkg = f"recursive_agents.{name}.{engine_name}"
    tools_pkg = f"recursive_agents.{name}.{tools_name}"

    files = {
        ENGINE_IPP_JSON: engine_dir / "IPP.json",
        ENGINE_IPP_OBJECT_SRC: engine_dir / "IPP_object.py",
        ENGINE_IPP_EXECUTOR_SRC: engine_dir / "IPP_executor.py",
        TOOLS_IPP_JSON: tools_dir / "IPP.json",
        TOOLS_IPP_OBJECT_SRC: tools_dir / "IPP_object.py",
        TOOLS_IPP_EXECUTOR_SRC: tools_dir / "IPP_executor.py",
        README_AGENT: agent_dir / "README.md",
        README_ENGINE: engine_dir / "README.md",
        README_TOOLS: tools_dir / "README.md",
        SYSTEM_PROMPT: agent_dir / "system_prompt.md",
    }
    for src, target in files.items():
        node_id = f"{name}_tools" if "tools" in target.name and \
            target.suffix == ".json" else f"{name}_engine"
        if target.name == "IPP.json":
            node_id = f"{name}_tools" if "tools" in str(target) else \
                f"{name}_engine"
        target.parent.mkdir(parents=True, exist_ok=True)
        target.write_text(
            render(src, name=name, node_id=node_id,
                   engine_pkg=engine_pkg, tools_pkg=tools_pkg,
                   level=level, generated_by=generated_by),
            encoding="utf-8")
    for d in (agent_dir, engine_dir, tools_dir):
        (d / "__init__.py").write_text(
            f'"""\n{name} — generated by {generated_by} (level {level}).\n"""\n',
            encoding="utf-8")
    # validate the F-files
    json.loads((engine_dir / "IPP.json").read_text(encoding="utf-8"))
    json.loads((tools_dir / "IPP.json").read_text(encoding="utf-8"))
    return engine_dir / "IPP.json", tools_dir / "IPP.json"
