"""
__TOOLS_PKG__ — the IPP Executors (Ξ_k) of the __AGENT_ID__ tools node.

Generated by __GENERATED_BY__ from the tools template. The base class
enforces ι → π → Ω → ι → ρ → τ* (Axiom X1–X9); the extras record the
tool identity + the target agent of the agent_* operations in the
hash-chained audit record.
"""
from __future__ import annotations

from IPP.IPP_executor import IPPExecutor


class ToolExecutor(IPPExecutor):
    """Ξ for a tool channel — records tool identity + target agent + the
    construction report fields."""

    def _record_extras(self, record: dict, envelope, out) -> None:
        payload = envelope.payload if isinstance(envelope.payload, dict) else {}
        if payload.get("agent_id"):
            record["target_agent"] = payload["agent_id"]
        if isinstance(out, dict):
            record["tool_ok"] = bool(out.get("ok", True))
            for key in ("verified", "constructed", "patches", "iterations",
                        "chain"):
                if key in out:
                    record[key] = out[key]
